spring:
  application:
    name: SmsScheduleSender
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect